### PR TITLE
ENH: adding __str__ and __repr__ methods to classes

### PR DESCRIPTION
**Pull request by spencerlyon2**
This is not quite finished. 

I am just opening this pull request so I can keep track of notes I collect as I go.

I will leave a comment saying it is ready to go at the appropriate time.

### CODE REVIEW

**Comment by spencerlyon2** [comment]
Comments so far:

* I don't have a great `__str__` method for `ARMA`. Any suggestions are welcome
* I am still struggling with how to represent attributes of the class that are functions. I would really like the `__repr__` methods to return a copy/pasteable string, but I don't know if this is possible. I tried using `inspect.getsource`, but that didn't work so well because it just returns the entire contents of each line containing the definition. For example, when I asked for the contents of `ConsumerProblem.du` it gave me [this whole line](https://github.com/QuantEcon/QuantEcon.py/blob/master/quantecon/models/ifp.py#L63), which also contains the definition of `ConsumerProblem.u`. I could manually parse it, but that seems like more work than we should be doing for this convenience feature and very fragile.

**Comment by spencerlyon2** [comment]
More comments:

* Because their arguments are mostly arrays, the idea of having `__repr__` return a string that can recreate the object is not feasible for the `Kalman`, `LAE`, `LQ`, and `ECDF`. I have just implemented somewhat meaningful `__str__` methods and am having `__repr__` just call `__str__` for now.

**Comment by spencerlyon2** [comment]
@oyamad 

The `DiGraph` class was contributed by you (thanks!) and I have I implemented very basic versions of these methods, feel free to change them if you think a different message would be better

**Comment by spencerlyon2** [comment]
@davidrpugh 

Given that you spend so much time on this code, I wanted to give you a chance to decide what should go into these method for the classes you wrote. Thus, I have left the following classes without these methods for now:

- `Model` (in model.py)
- `CESModel` (in ces.py)
- `CobbDouglassModel` (in cobb_douglass.py)
- `ImpulseResponse` (in impulse_response.py)
- `IVP` (in ivp.py)

Please let me know if you would like to write these methods yourself if you want me to try to figure out something reasonable. 

Thanks!

**Comment by spencerlyon2** [comment]
At this point we just need to implement the display methods for the classes indicated in the checklist in the previous comment to @davidrpugh . All other classes are ready to go.

So, once we have finished with those, this PR should be ready to merge.

**Comment by davidrpugh** [comment]
@spencerlyon2 

Thanks for the heads up. I will look at this later this evening.

**Comment by davidrpugh** [comment]
@spencerlyon2 

I have commited the changes locally and pushed them to my fork of the `quantecon` repo, but the commits are not showing up here. Somehow the `repr` branch in my fork seems to have become detached from the `repr` branch here.  Thoughts?

**Comment by spencerlyon2** [comment]
The little note below your comment says `Add more commits by pushing to the repr branch on QuantEcon/QuantEcon.py.`

I'll just pull changes down from your repo and push to this one.

**Comment by davidrpugh** [comment]
@spencerlyon2 

Weird. I didn't see any such note. In any case I initially tried
```
git push -u https://github.com/QuantEcon/QuantEcon.py.git/repr
```
this failed due to insufficient permissions.

**Comment by davidrpugh** [comment]
Also I haven't yet added anything to the `IVP` class yet.  The constructor takes functions as inputs and there aren't any parameters per se.  Do you have any ideas?

**Comment by spencerlyon2** [comment]
I'm not sure you have push permissions to QuantEcon/QuantEcon.py, that might why that failed. It was the right idea though.

If there really isn't any useful information to print for the ivp class you could leave it without a display method -- I'd be totally fine with that.

**Comment by oyamad** [comment]
@spencerlyon2 Re: `DiGraph`

Very good, thanks!

**Comment by spencerlyon2** [comment]
@jstac I think this is ready.

Feel free to merge when you have had a chance to look over it.

**Comment by jstac** [comment]
This is really neat, thank you!

**Pull request merged**
