### PR TITLE
MAINT: Fix pytest warnings and use pytest in Conda CI

### PR DESCRIPTION
**Pull request by Smit-create**
https://github.com/QuantEcon/QuantEcon.py/issues/539#issuecomment-1084615625

### CODE REVIEW

**Review by oyamad — COMMENTED** [review]
@Smit-create Thanks!
Do you see why the test coverage is indicated 0%?

**Comment by Smit-create** [comment]
Here it shows 95%: https://coveralls.io/builds/47813218

**Comment by mmcky** [comment]
I am not sure why the `coveralls` badge is showing 0% here. 

When you click through the link it says: "Coverage remained the same at 0.0%"

I will try running this locally -- must be an issue with `coveralls` action perhaps?

**Comment by mmcky** [comment]
My local `cover` report is `88%` so some metric isn't being consistent. 

```
Name                                                           Stmts   Miss  Cover   Missing
--------------------------------------------------------------------------------------------
quantecon/__init__.py                                             33      2    94%   8-9
quantecon/arma.py                                                 73     34    53%   72-75, 79-98, 102, 106-107, 111, 115-116, 144, 151-152, 206-210, 224-228
quantecon/ce_util.py                                              20      0   100%
quantecon/compute_fp.py                                          135      7    95%   26, 108, 111, 151, 202, 232, 277
quantecon/discrete_rv.py                                          18      1    94%   37
quantecon/distributions.py                                        30      0   100%
quantecon/dle.py                                                 141     55    61%   195-248, 265-296
quantecon/ecdf.py                                                 12      2    83%   33-34
quantecon/estspec.py                                              39      0   100%
quantecon/filter.py                                               16      0   100%
quantecon/game_theory/__init__.py                                 11      0   100%
quantecon/game_theory/game_generators/__init__.py                  2      0   100%
quantecon/game_theory/game_generators/bimatrix_generators.py      71      0   100%
quantecon/game_theory/lemke_howson.py                             29      0   100%
quantecon/game_theory/mclennan_tourky.py                          68      0   100%
quantecon/game_theory/normal_form_game.py                        247     42    83%   170, 191-195, 379-380, 493, 675-677, 682, 688-690, 704, 711-713, 717-721, 778, 834-838, 842-859
quantecon/game_theory/pure_nash.py                                 7      0   100%
quantecon/game_theory/random.py                                   35      0   100%
quantecon/game_theory/repeated_game.py                            51      5    90%   73, 76, 81, 121, 163
quantecon/game_theory/support_enumeration.py                      13      0   100%
quantecon/game_theory/utilities.py                                10      3    70%   38-39, 53
quantecon/game_theory/vertex_enumeration.py                       46      0   100%
quantecon/graph_tools.py                                         166      3    98%   129, 142, 175
quantecon/gridtools.py                                            40      0   100%
quantecon/inequality.py                                           15      1    93%   118
quantecon/ivp.py                                                  55      3    95%   62-64, 82
quantecon/kalman.py                                               93     39    58%   85-90, 94-96, 100-102, 158-179, 294-313, 317-321
quantecon/lae.py                                                  15      2    87%   56-60
quantecon/lqcontrol.py                                           160     11    93%   148, 157-166, 306-308, 331-334
quantecon/lqnash.py                                               47      2    96%   150-151
quantecon/lss.py                                                 129     32    75%   115, 121, 138, 144-150, 196-197, 238-239, 268-283, 333, 369-373, 399-411
quantecon/markov/__init__.py                                       8      0   100%
quantecon/markov/_ddp_linprog_simplex.py                           5      0   100%
quantecon/markov/approximation.py                                 44      1    98%   126
quantecon/markov/core.py                                         217      6    97%   219, 232, 482-485, 499, 502
quantecon/markov/ddp.py                                          282     15    95%   312, 316, 327, 329, 332, 334, 337, 392, 396, 427, 537, 772, 1002-1003, 1017
quantecon/markov/gth_solve.py                                     23     12    48%   71-91
quantecon/markov/random.py                                        48      0   100%
quantecon/markov/utilities.py                                      2      0   100%
quantecon/matrix_eqn.py                                          108      7    94%   85-86, 92-93, 194-195, 211
quantecon/optimize/__init__.py                                     6      0   100%
quantecon/optimize/linprog_simplex.py                             18      0   100%
quantecon/optimize/minmax.py                                       4      0   100%
quantecon/optimize/nelder_mead.py                                  4      0   100%
quantecon/optimize/pivoting.py                                     5      0   100%
quantecon/optimize/root_finding.py                                10      0   100%
quantecon/optimize/scalar_maximization.py                          2      0   100%
quantecon/quad.py                                                125      9    93%   27, 32-35, 176, 268, 273, 292, 535
quantecon/quadsums.py                                             14      0   100%
quantecon/random/__init__.py                                       2      0   100%
quantecon/random/utilities.py                                     32      6    81%   84-89
quantecon/rank_nullspace.py                                       15      0   100%
quantecon/robustlq.py                                            101      7    93%   78-86, 351-356
quantecon/util/__init__.py                                         5      0   100%
quantecon/util/array.py                                            1      0   100%
quantecon/util/combinatorics.py                                    9      0   100%
quantecon/util/notebooks.py                                       29      3    90%   85, 88, 97
quantecon/util/numba.py                                            7      2    71%   9-10
quantecon/util/random.py                                          10      1    90%   31
quantecon/util/timing.py                                          69     50    28%   34-36, 57-70, 90-103, 140-172, 179, 183, 187, 191
--------------------------------------------------------------------------------------------
TOTAL                                                           3032    363    88%
----------------------------------------------------------------------
Ran 476 tests in 119.429s
```

**Comment by Smit-create** [comment]
@mmcky @oyamad Coveralls and CI are green again!

**Review by oyamad — APPROVED** [review]
Great!

**Pull request merged**
