### PR TITLE
Add sample game generators from bimatrix-generators

### PR DESCRIPTION
**Pull request by oyamad**
For the background, see https://github.com/QuantEcon/Games.jl/issues/53#issue-260613877. Cc: @ptigwe

- [x] Generate doc files

### CODE REVIEW

**Comment by oyamad** [comment]
@mmcky Running `python qe_apidoc.py` does not generate doc files for `bimatrix_generators.py` which is located in a subdirectory `game_generators` in `game_theory`. Could you give an instruction, to me or to @QBatista, about how to modify [`qe_apidoc.py`](https://github.com/QuantEcon/QuantEcon.py/blob/master/docs/qe_apidoc.py)?

**Comment by mmcky** [comment]
Thanks @oyamad. @QBatista we can work on this tomorrow, and I will update on how qe_apidoc.py is put together. I haven't documented it well as I was hoping to make it automated (to prevent things not being included) using `autodoc`.

**Comment by mmcky** [comment]
The issue is that our ``qe_apidoc.py`` only implements one level deep and the directory tree is not recursively searched. To get this PR merged we can add this sub-module into ``qe_apidoc.py`` to get the documentation to build.

**Comment by oyamad** [comment]
If we add something like

```py
game_theory_files += glob("../quantecon/game_theory/[!tests]*/[a-z0-9]*.py")
```

to
https://github.com/QuantEcon/QuantEcon.py/blob/931fd11ecd4ba3a8db10c605aa348c6015c2543e/docs/qe_apidoc.py#L187

would that work?

**Comment by mmcky** [comment]
That is essentially what needs to be done - except that would list the generators under the ``game_theory`` section and not as another sub-directory within `game_theory`.

**Comment by oyamad** [comment]
I see. At the moment it is fine with me: the functions in `game_theory/game_generators/bimatrix_generators.py` are imported into the `qe.game_theory` submodule (i.e., they can be called by `qe.game_theory.*`).

**Comment by mmcky** [comment]
I see. In that case: 

```
game_theory_files += glob("../quantecon/game_theory/game_generators/[a-z0-9]*.py")
```

should work.

**Comment by mmcky** [comment]
It's also OK if you want to use your pattern to capture future sub-directories also if you think the sub-modules will always be available at the top level of the `game_theory` module.

**Comment by oyamad** [comment]
`make html` does not work with this approach: `ModuleNotFoundError: No module named 'quantecon.game_theory.bimatrix_generators'`

**Comment by mmcky** [comment]
@oyamad this isn't elegant but includes the game_generators subdirectory into the ``qe_apidoc.py`` tool. I would like to rewrite this to be recursive and search the directory tree automatically but this manually adds that directory and then adds the ``bimatrix_generators`` module to the game_theory toc to keep the toc flat. 

image

As this branch sits in your fork I don't think I can pre-render using ``rtd`` (as a version) for you to have a look at but it does render locally (assuming you have your version of quantecon installed or is active in an environment).

**Comment by oyamad** [comment]
@mmcky Great, thanks so much! It renders perfectly locally, although there is some warning with `make html`:

```
:1: (WARNING/2) Inline interpreted text or phrase reference start-string without end-string.
```

(Does not seem to affect the outcome.)

**Comment by mmcky** [comment]
Hi @oyamad - Great. I am comfortable with the warning from sphinx for now and happy for this to be merged when you're ready.

**Comment by oyamad** [comment]
There remain some English grammatical (common for this PR and QuantEcon/Games.jl#76).

Could you advise us on
* https://github.com/QuantEcon/Games.jl/pull/76#discussion_r174618369
* https://github.com/QuantEcon/Games.jl/pull/76#discussion_r174623559

Thanks!

**Comment by oyamad** [comment]
This is ready to be merged.

**Comment by oyamad** [comment]
Many thanks @QBatista  @shizejin @mmcky !

**Pull request merged**
