### PR TITLE
General cleanup of Package

### PR DESCRIPTION
**Pull request by mmcky**
this fixes https://github.com/QuantEcon/QuantEcon.py/issues/410

### CODE REVIEW

**Comment by oyamad** [comment]
Maybe add `\n` to this line: https://github.com/QuantEcon/QuantEcon.py/blob/88252ce9fca2fdee49c296e376ab183fdc597fdb/setup.py#L18

```py
    doc += "\nversion = '%s'\n" % VERSION
```

**Comment by mmcky** [comment]
@oyamad I think this address all the items listed in #410. Thanks for adding those issues there. 

In addition to the issue:

1. I have removed `data/` from the root level and migrated the only used file `employment.csv` to `quantecon/tests/data`
1. swapped over to solely use `setuptools`
1. added package discovery using `find_packages()`
1. added `MANIFEST.in` for data inclusions.

**Comment by mmcky** [comment]
shoot I should have squashed and merged. @oyamad would you mind if I made this the default?

**Comment by oyamad** [comment]
No problem.

**Pull request merged**
