### PR TITLE
Isolate rtd-specific requirements to doc-requirements.txt

### PR DESCRIPTION
**Pull request by rht**
There are too many requirements in order to build the docs. However, there is no way to test if this patch works unless it is merged, so I am merging it into the `update-docs` branch.

### CODE REVIEW

**Comment by rht** [comment]
(ok, I found that the builds are triggered only on master: https://readthedocs.org/projects/quanteconpy/builds/)

**Comment by mmcky** [comment]
thanks for tidying this up @rht. Once `rtd` registers this PR I can build it as a version to test before merging with `master`

**Comment by oyamad** [comment]
`statsmodels` is no longer used, so can be removed from `pip-requirements.txt`.

**Comment by mmcky** [comment]
hey @rht sorry just realised this was PR setup to merge into update-docs. I'll review and merge to master instead. Thanks for the cleanup on this.

**Comment by mmcky** [comment]
hey @rht is it easy to update this to point at master rather than `update-docs` branch? If not I'll migrate changes into master.

**Comment by rht** [comment]
OK, I will move it to be onto master.

**Pull request closed without merging**
