### PR TITLE
Update build status badge to GitHub Actions

### PR DESCRIPTION
**Pull request by rht**

### CODE REVIEW

**Comment by rht** [comment]
If you look at https://github.com/QuantEcon/QuantEcon.py/workflows/continuous-integration/badge.svg, the phrase "continuous integration" seems to be too verbose. Maybe rename it to CI or "build", like Travis does?

**Comment by mmcky** [comment]
thanks @rht I would be ok with changing this to `build`

**Comment by rht** [comment]
I added a second commit which renames to "build". The changes will only take effect after this PR is merged.

**Comment by rht** [comment]
https://github.com/QuantEcon/QuantEcon.py/workflows/build/badge.svg

**Comment by mmcky** [comment]
🎉 -- thanks @rht

**Pull request merged**
