### PR TITLE
[GitHub Actions] Setup Tests via Github Actions

### PR DESCRIPTION
**Pull request by rht**

### CODE REVIEW

**Comment by rht** [comment]
(whoops, I was about to make this PR on my fork instead of here!)
Oh well, anyway, since travis-ci.org is gone, we need to switch to another CI.

**Comment by rht** [comment]
@Harveyt47 @mmcky I finally got 94.15% from coveralls.io: https://github.com/QuantEcon/QuantEcon.py/pull/561/checks?check_run_id=1633166620#step:7:15 -> https://coveralls.io/jobs/72880434.

**Comment by rht** [comment]
My fix is to do according to this comment: https://github.com/coverallsapp/github-action/issues/4#issuecomment-727600521.

**Comment by rht** [comment]
Let me know if the commits need to be squashed. They are kind of messy.

**Comment by mmcky** [comment]
thanks @rht!. We will definitely Squash these commits. One question before we merge -- I see you added a GitHub Repo Secret for the Tokens Coveralls. Just wondering if we should use a `quantecon` account -- I am guessing that is a personal token?

**Comment by rht** [comment]
> I see you added a GitHub Repo Secret for the Tokens Coveralls.

Nope, I was in fact removing it.
According to the readme of https://github.com/AndreMiras/coveralls-python-action
this is the default value of `GITHUB_TOKEN`:
> Default: ${{ github.token }}

**Comment by rht** [comment]
Also, I removed .coveralls.yml instead, so it is no longer tied to travis-ci.

**Comment by rht** [comment]
I added another commit to remove pytest since it is no longer used in the latest version of this PR.

**Comment by Harveyt47** [comment]
Thanks @rht I struggled with the coveralls.io a bit. Is this still running `nose` and not `pytest`

**Comment by rht** [comment]
Yes, this is still running `nose`. If you want to migrate to `pytest`, I think we can do that in another PR.

**Comment by rht** [comment]
Ready to be squashed.

**Comment by mmcky** [comment]
Thanks @rht -- it will be nice to have tests via GitHub Actions.

**Pull request merged**
