### PR TITLE
Change 'is' to '=='

### PR DESCRIPTION
**Pull request by MKobayashi23m**
Fix [this alert](https://lgtm.com/projects/g/QuantEcon/QuantEcon.py/snapshot/40f9ce61ccea537800e4338ba9f050c2bc232023/files/quantecon/util/random.py?sort=name&dir=ASC&mode=heatmap#L25).

### CODE REVIEW

**Comment by oyamad** [comment]
@MKobayashi23m Thanks for the fix, but please rebase on the `master` branch.

**Comment by MKobayashi23m** [comment]
> @MKobayashi23m Thanks for the fix, but please rebase on the `master` branch.

Thank you for your remark!

**Comment by oyamad** [comment]
@MKobayashi23m Thanks, but I should have thought more carefully about this alert: Now I wonder `is` is more appropriate in this usecase and the report by `lgtm` is a false positive.

**Comment by MKobayashi23m** [comment]
> @MKobayashi23m Thanks, but I should have thought more carefully about this alert: Now I wonder `is` is more appropriate in this usecase and the report by `lgtm` is a false positive.

Oh, I should have, too... Thank you again for your comment. I learned many things from this.
I will close this PR soon.

**Pull request closed without merging**
