### PR TITLE
Fixes for examples and solutions notebook

### PR DESCRIPTION
**Pull request by mmcky**
This branch is applying fixes for broken ``examples`` and ``solutions`` notebooks.

Broken
----------
  1. ``examples/paths_and_hist.py``
  1. ``examples/robust_monopolist.oy``
  1. ``examples/lakemodel_example.py``
  1. ``solutions/lakemodel_solutions.ipynb``

Fixed
-------
  1. ``examples/lakemodel_example.py`` => Added ``lakemodel.py`` to quantecon library for use by this example and the related solutions notebook. 
  1. ``solutions/lakemodel_solutions.ipynb`` => Same as above. 

In addition this PR improves the reporting on the command line.

### CODE REVIEW

**Comment by mmcky** [comment]
@cc7768 Any ideas why ``robust_monopolist.py`` is not failing to converge? I looked at the history of the ``robust_monopolist.py`` but it isn't immediately apparent to me. 

```python
Traceback (most recent call last):
  File "robust_monopolist.py", line 130, in <module>
    Po, Fo, do = optimal_lq.stationary_values()
  File "/home/matthewmckay/anaconda/lib/python2.7/site-packages/quantecon/lqcontrol.py", line 209, in stationary_values
    P = solve_discrete_riccati(A0, B0, R, Q, N)
  File "/home/matthewmckay/anaconda/lib/python2.7/site-packages/quantecon/matrix_eqn.py", line 197, in solve_discrete_riccati
    raise ValueError(fail_msg.format(i))
ValueError: Convergence failed after 501 iterations.
```

**Comment by cc7768** [comment]
@mmcky I looked around, but nothing changed within that file should break it -- At some point we may have changed the order of arguments for `solve_discrete_riccati`. Could that be it?

Notice:
* In the `LQ` class we call https://github.com/QuantEcon/QuantEcon.py/blob/master/quantecon/lqcontrol.py#L209
* But we call them different things in `solve_discrete_riccati` https://github.com/QuantEcon/QuantEcon.py/blob/master/quantecon/matrix_eqn.py#L100

This may have been on purpose; I don't remember whether Q and R are the same in `LQ` and `solve_discrete_riccati` (I remember being confused at one point about them). Off the top of my head that's best suggestion I have. I can look into it more later if it turns out to not be the problem.

**Comment by mmcky** [comment]
@cc7768 That is a little odd. I had a quick look into this and tried swapping them but then you get a ``lining`` problem. So it doesn't immedietly seem like a quick fix.

```python
Traceback (most recent call last):
  File "examples/robust_monopolist.py", line 130, in <module>
    Po, Fo, do = optimal_lq.stationary_values()
  File "/home/matthewmckay/anaconda/lib/python2.7/site-packages/quantecon/lqcontrol.py", line 209, in stationary_values
    P = solve_discrete_riccati(A0, B0, Q, R, N)
  File "/home/matthewmckay/anaconda/lib/python2.7/site-packages/quantecon/matrix_eqn.py", line 166, in solve_discrete_riccati
    Q_tilde = - Q + dot(N.T, solve(Z, N + gamma * BTA)) + gamma * I
  File "/home/matthewmckay/anaconda/lib/python2.7/site-packages/numpy/linalg/linalg.py", line 381, in solve
    r = gufunc(a, b, signature=signature, extobj=extobj)
  File "/home/matthewmckay/anaconda/lib/python2.7/site-packages/numpy/linalg/linalg.py", line 90, in _raise_linalgerror_singular
    raise LinAlgError("Singular matrix")
numpy.linalg.linalg.LinAlgError: Singular matrix
```

**Comment by mmcky** [comment]
Introduced dimension checking on input for ``lss.py`` picked up two other files where the ``C`` vector should be column and not row. Fixes for ``tsh_hg.py`` and ``paths_and_stationarity.py`` submitted.

**Comment by mmcky** [comment]
With only one example left to fix ``example/robust_monopolist.py`` I propose we merge this branch to incorporate current fixes and open an issue to track the last item.

**Comment by jstac** [comment]
@mmcky Many thanks.

**Pull request merged**
