### PR TITLE
Migrate applications .. examples/ and quantecon/models/ to QuantEcon.applications

### PR DESCRIPTION
**Pull request by mmcky**
Status: **NOT READY TO BE MERGED**

This PR removes content that has been migrated to the ``QuantEcon.applications`` repository. 

The following folders were migrated:
  - ``examples/``
  - ``quantecon/models``
  - ``quantecon/tests/test_models/``
  - ``quantecon/scripts``

This should **NOT** be merged until associated PR's have been submitted to adjust lectures repository to point to new code locations organised by topic within ``QuantEcon.applications``

### CODE REVIEW

**Comment by mmcky** [comment]
Related PRs:
https://github.com/QuantEcon/QuantEcon.jl/pull/79

**Comment by mmcky** [comment]
This ``PR`` is now pending successful reconfiguration of lectures and the re-organisation of ``QuantEcon.applications`` to be in the final format.

This should be merged with:
  1. Reconfigure ``QuantEcon.applications``
  2. Reconfigure Lectures

**Comment by mmcky** [comment]
Should we add an Deprecation Error in the event someone tries to import ``quantecon.models``?

**Comment by mmcky** [comment]
**Reminder:** Once this is merged, should also delete ``relocate_models`` branch

**Comment by mmcky** [comment]
Merging this PR will break the current live website. 
This should be merged once the website has been migrated.

**Comment by mmcky** [comment]
Added Deprecation notification for users trying to import ``quantecon.models``

```python
Python 3.5.0 |Anaconda 2.4.0 (64-bit)| (default, Oct 19 2015, 21:57:25) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import quantecon.models
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/matthewmckay/repos-collab/QuantEcon.py/quantecon/models/__init__.py", line 1, in <module>
    raise ImportError("The quantecon.models subpackage has been migrated to the QuantEcon.applications (https://github.com/QuantEcon/QuantEcon.applications)")
ImportError: The quantecon.models subpackage has been migrated to the QuantEcon.applications (https://github.com/QuantEcon/QuantEcon.applications)
```

**Comment by mmcky** [comment]
@sglyon My suggestion re: PR's to remove the ``examples`` and ``models```. Let's accept these in 2 days time on both ``QuantEcon.jl`` and ``QuantEcon.py``. This way if we find some errors in the site - it is possible to revert the html really easily if these repo's haven't changed yet. Once the ``html`` code is in production for the week we can then accept these PRs

**Comment by mmcky** [comment]
@jstac This looks good to merge. The ``QuantEcon.applications`` repo has been setup and is now linked in with the quant-econ.net. This repo now holds all ``example/`` code and relevant ``solutions/`` notebooks in topic based folders. 

Unless there are any further comments I will merge this branch tomorrow. The equivalent ``QuantEcon.jl`` has already been merged.

**Comment by jstac** [comment]
Please go ahead.  Thanks.

**Pull request merged**
