### PR TITLE
FEAT: Add random_state option (issue #153)

### PR DESCRIPTION
**Pull request by QBatista**
Address #153

As a first step, here are some changes adding a random_state option to arma.py (issue #153). If the approach is appropriate, I have already written the code for the other remaining files.

### CODE REVIEW

**Comment by oyamad** [comment]
@QBatista Rebase this on `master` (or merge `master`).

**Comment by mmcky** [comment]
@lbui01 is this random state feature going to interfere with any work you're doing on random seed (or is that primarily to support lecture site)?

**Comment by mmcky** [comment]
thanks @QBatista this is a nice addition to ``arma``

**Comment by jstac** [comment]
@lbui01 is focused on the lecture site.
@QBatista : many thanks

**Pull request merged**
