### PR TITLE
DiscreteDP: further fix in docstring

### PR DESCRIPTION
**Pull request by oyamad**
Fix the remaining mistakes from #198:

* Correct `..math::` by `.. math::`.
* Replace `\beta \in [0, 1)` with `0 \leq \beta < 1`.

### CODE REVIEW

**Comment by spencerlyon2** [comment]
any idea why travis is complaining?

**Comment by mmcky** [comment]
This is an odd one. Looking at the logs it seems the build environment is failing

    The command "conda update --yes conda" failed and exited with 127 during .

**Comment by mmcky** [comment]
Just ``closing`` to force a rebuild through Travis CI

**Comment by mmcky** [comment]
Currently the build environment does not appear to be installing ``conda`` correctly.  

    /home/travis/build.sh: line 41: conda: command not found

Will test with a different PR coming down the pipeline.

**Comment by mmcky** [comment]
@oyamad thanks for the update to ``miniconda``. Travis is now working as expected. Merging now.

**Pull request merged**
