### PR TITLE
fixed .size error

### PR DESCRIPTION
**Pull request by sbarratt**
.size does not exist for tuples. Replaced with len

### CODE REVIEW

**Comment by cc7768** [comment]
Thanks for submitting this! Great for people to see these types of things and leave some feedback. 

If I'm not mistaken (which is possible), `q` should be a numpy array. Maybe instead of changing from `.size` to `len` we should make sure the input is a numpy array (or change it to one). @jstac @mmcky @spencerlyon2 @oyamad any thoughts?

**Comment by sbarratt** [comment]
You could do:

```python
self._q = np.array(q)
```

**Comment by oyamad** [comment]
Or,

```python
self._q = np.asarray(q)
```

which does not make a copy when `q` is already a numpy array.

Otherwise, if one wants to keep `.size` (and `self._q` as is), could do `n=self.Q.size`, where `self.Q` is a numpy array.

**Comment by jstac** [comment]
@oyamad 's first suggestion sounds good.  Just waiting for some major reorganizations of the repo and lectures to finish and then we can make this change.  @sbarratt Many thanks.

**Comment by jstac** [comment]
@sbarratt Thanks again for flagging this.  I'm closing the PR but we'll make the fix suggested above.

**Pull request closed without merging**
