### PR TITLE
DOC: Generate doc files for game_theory

### PR DESCRIPTION
**Pull request by oyamad**
* I forgot to run `python qe_apidoc.py` when I added the recent routines to `game_theory`.
* Prepend `_` to private functions, in order for them not to show up in the documentation.

### CODE REVIEW

**Comment by mmcky** [comment]
@oyamad Thanks for this. Good pickup. I need to add readthedocs to my checklist. The passes all the builds -- does it render on your machine nicely? If so I will just go ahead and merge.

**Comment by oyamad** [comment]
Please do merge; it looks fine on my machine.

**Comment by mmcky** [comment]
Great. Thanks. Merging now

**Comment by oyamad** [comment]
(I would like to delegate #287 to somebody else...)

**Comment by mmcky** [comment]
roger that. Thanks for the ``warnings`` report.

**Pull request merged**
