### PR TITLE
CI: Add a CI job for testing using conda

### LINKED ISSUE #514: Update GitHub Actions to check against latest Anaconda Distribution
As we recommend users to use `anaconda` we should update ~~`travis`~~ `github` to use the latest `anaconda` distribution. This will be slower for `CI` but more consistent with user reports of versions (particularly relating to `numba` errors and issues)

### PR DESCRIPTION
**Pull request by Smit-create**
Fixes #514 

cc @mmcky

### CODE REVIEW

**Comment by mmcky** [comment]
thanks @Smit-create this is looking great -- really appreciate it.

I have approved for `GitHub actions` to run this PR.

**Comment by Smit-create** [comment]
> this is looking great

Thanks! This seems to be working fine. We can also use `conda` environment cache for faster CI (not that effective in case of `mac`) but we can do it as the follow up of this PR.

**Comment by mmcky** [comment]
Thanks @Smit-create -- the Conda cache idea is also great 👍 - thanks for your contribution.

**Comment by mmcky** [comment]
- [ ] We might also deprecate the old `testing`

**Pull request merged**
