### PR TITLE
Remove warnings supression as noted by Issue #229

### PR DESCRIPTION
**Pull request by mmcky**
This PR removes the warning supression from `arma.py` and `matrix_eqn.py`.

**TODO:** The next step is to fix the underlying cause of the warning.

### CODE REVIEW

**Comment by mmcky** [comment]
The ``arma`` warnings are a result of:

```python
w, spect = self.spectral_density(two_pi=False)
```

the ``spect`` array is complex. With the example on the ``quant-econ.net`` page the coeeficient on the ``j`` term are all zero. In general is it safe to use the real component of this array? If so we can add a.real on spec to send matplotlib an array of reals.

**Comment by mmcky** [comment]
Moving related comments here from Issue #229 

Comment in ``arma.py``

```python
# == Ignore unnecessary warnings concerning casting complex variables back to
# floats == #
```
@jstac In general is it safe to use the real component of this array?

**Comment by mmcky** [comment]
Comment in ``matrix_eqn.py``

```python
# == Suppress warnings from checking conditioning of matrices == #
```

**Comment by mmcky** [comment]
@jstac would you mind reviewing this spectral density question when you have time? Its in relation to some warnings we are trying to remove in the quantecon.py package.

**Comment by oyamad** [comment]
What is the status of this PR?

**Comment by oyamad** [comment]
Is it possible to merge this PR as is and open another issue for discussion on arma.py and matrix_eqn.py? I find it a bit annoying that warnings are all ignored in the whole session once `quantecon` is imported...

**Comment by mmcky** [comment]
Sure. I will have a quick review of this this afternoon to double check that all of the suppression statements have been removed and then I will setup a separate issue to fix ``arma.py`` and ``matrix_eqn.py``.

**Comment by oyamad** [comment]
Thanks!

**Comment by mmcky** [comment]
This looks ready to merge (passes tests).

Note: this will cause warnings to appear when using the library. 

https://github.com/QuantEcon/QuantEcon.py/issues/271
https://github.com/QuantEcon/QuantEcon.py/issues/272

**Pull request merged**
