### PR TITLE
Numba version of mc_sample_path/MarkovChain.simulate

### PR DESCRIPTION
**Pull request by oyamad**
This is to follow #137:

I am very sorry, but I have been busier than I had expected. I wanted to get everything prepared as I was going to try a little different implementation against our discussion in some aspects, but I could not have found enough time. Anyway here's a preliminary first draft for discussion, where I am absolutely open to suggestions.

0. The loop version of `np.searchsorted` for jitting (tentatively called `search_cdf`) is pulled out from the main routine, where auto loop-jitting still works (I confirmed this by the html annotation feature; thanks @albop for the information!).

0. `search_cdf` might better be called `searchsorted`, in which case, it should work like `np.searchsorted` (the current code assumes that `v` is always smaller than `cdf[-1]`). (Docsting is yet to be written.)

0. I haven't written code for switching to a NumPy version. The current `mc_sample_path` works with NumPy by only redefining `search_cdf` to be `lambda cdf, v: np.searchsorted(cdf, v, side='right')`, so I was hesitating duplicating the whole code.

0. `cdfs` once computed may be stored in the `MarkovChain` instance. In that case, the code should be placed in the `simulate` method of `MarkovChain`, and `mc_sample_path` will just return `MakovChain(P).simulate(init, sample_size)`.

0. Motivated by a comment by @albop I was thinking of changing the API, for example by giving `MarkovChain` a method `replicate` in addition to `simulate`, as in [LinearStateSpace](https://github.com/QuantEcon/QuantEcon.py/blob/master/quantecon/lss.py#L68).

0. This is a different issue, but I wonder if there would be demand for a version of this function that is specialized for a sparse matrix input. That would use `search_cdf`, too.

### CODE REVIEW

**Comment by mmcky** [comment]
Hi @oyamad thanks - no problem - my original thought on workflow was that we could work together on a common branch in the main QuantEcon.py repo called something like ``numba`` or  ``numba-improvements`` in which we could jointly edit and progress towards a final implementation based on your two examples. This is the workflow that I am familiar with in which we can pull the branch down make some edits and commit them to the branch for review etc. Once we are happy with the final implementation we can then issue a PR to the master branch for inclusion of the feature.

Is there a better way to do this?  Can I submit edits directly to ``oyamad:mc_sample_path_numba`` or is this PR effectively a branch? I am happy to learn if that is a better model.

**Comment by jstac** [comment]
@oyamad It's very nice code.  

I think it would be good to have a `replicate` function, if it's not too much work.  I'm not sure about the demand for working with sparse matrices but it seems likely these matrices are common in applied problems.

I'm looking forward to seeing the PR.

**Comment by jstac** [comment]
@mmcky If you have time it would be great if you could implement #133 as part of that `numba_improvements` branch you mention (and close the issue once it's done).

**Comment by oyamad** [comment]
@mmcky Sure let's follow the workflow as you describe.
I think I have succeeded in creating a branch `numba_improvements` in the main QuantEcon.py repo.

Closing.

**Pull request closed without merging**
