### PR TITLE
MAINT: Increase the tolerance bound to fix failing tests

### LINKED ISSUE #607: CI failing on Master Branch
It looks like `Conda` tests are failing on the `master` branch. 

This will need to be fixed before any other PR's are merged 

cc @Smit-create

### PR DESCRIPTION
**Pull request by Smit-create**
Fixes #607

### CODE REVIEW

**Comment by Smit-create** [comment]
@mmcky The PR looks ready for a review!

**Comment by mmcky** [comment]
thanks @Smit-create I will try and track down who wrote this routine and see if they are happy with the change. I tend to think the tolerances for a single test should be the same -- unless there is a good reason for them to be different and I see the `assert` below it has a similar tolerance.

**Comment by mmcky** [comment]
@Smit-create other test runs seem to have no issue now. Can we close this PR?

**Comment by Smit-create** [comment]
Sure!

**Pull request closed without merging**
