### PR TITLE
Add Numba jit version of scipy.special.comb

### PR DESCRIPTION
**Pull request by oyamad**
1. Add `comb_jit`, Numba jit version of `scipy.special.comb`
   Returns `0` if the outcome exceeds the maximum value of `np.intp`
2. Add `num_compositions_jit` which uses `comb_jit`
3. Compile `simplex_grid` in nopython mode using `num_compositions_jit`

### CODE REVIEW

**Comment by mmcky** [comment]
thanks @oyamad. Sorry I have been off grid for a couple of weeks. I will merge this later today.

**Comment by oyamad** [comment]
@mmcky No problem at all!
(Upon merge, it would be nice if you merge the commits as they are without squashing; these commits are logically separate.)

**Comment by mmcky** [comment]
Thanks @oyamad for letting me know. Does this PR rely on #375 to be merged first?

**Comment by oyamad** [comment]
@mmcky These PRs are independent. Either PR can be merged first.

**Comment by mmcky** [comment]
@oyamad when you get a chance would you mind reviewing this merge conflict. Thanks.

**Comment by oyamad** [comment]
@mmcky Rebased on `master`. Thanks.

**Pull request merged**
