### PR TITLE
DOC: fix doxstring for compte_sequence in lqcontrol

### PR DESCRIPTION
**Pull request by sglyon**
Wasn't true!

### CODE REVIEW

**Comment by mmcky** [comment]
@spencerlyon2 Just processing all open PRs. Is this still an issue?

**Comment by spencerlyon2** [comment]
Not sure. I'd have to look again. Want me to check it out?

**Comment by mmcky** [comment]
@spencerlyon2 there aren't many changes. It looks like you have converted to using ``np.random.randn`` rather than some ``dot`` function in addition to updating the docstring.

**Comment by spencerlyon2** [comment]
I think it is still meaningful. In the docstring we claimed to be returning the w_t, but we were actually returning C * w_t 

Also the number of elements in the return value was incorrectly documented.

**Comment by mmcky** [comment]
Cool - I will replicate the changes and push them.

**Comment by mmcky** [comment]
@spencerlyon2 I rebased this change but it is failing the test.

```python
 ======================================================================
FAIL: test_scalar_sequences (quantecon.tests.test_lqcontrol.TestLQControl)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/QuantEcon/QuantEcon.py/quantecon/tests/test_lqcontrol.py", line 61, in test_scalar_sequences
    assert_allclose(x_1, x_seq[0, -1], rtol=1e-4)
  File "/home/travis/miniconda/lib/python2.7/site-packages/numpy/testing/utils.py", line 1297, in assert_allclose
    verbose=verbose, header=header)
  File "/home/travis/miniconda/lib/python2.7/site-packages/numpy/testing/utils.py", line 665, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=0.0001, atol=0
(mismatch 100.0%)
 x: array([[ 0.146818]], dtype=float32)
 y: array(0.932981936024652)
```

**Comment by spencerlyon2** [comment]
@mmcky sorry, I don't really have time to track down the error.

**Pull request closed without merging**
