### PR TITLE
fix timing utility docstrings for tic toc tac

### LINKED ISSUE #314: Fix: Tic/Tac/Toc Utility
Docstrings in Tic/Tac/Toc need to be updated.

### PR DESCRIPTION
**Pull request by mmcky**
``tac`` and ``toc`` docstrings were incorrect. 

fixes #314

### CODE REVIEW

**Comment by albop** [comment]
The docstring are OK. Looking at these functions again made me think one might sometime want to not print the elapsed time. Could be either `toc(verbose=False)` or (like in Julia) `toq`. Does it sound useful ?

**Comment by natashawatkins** [comment]
I agree - I think there could be some useful improvements to these functions such as suppressing output, adjusting units, choosing precision, etc.

**Comment by albop** [comment]
@natashawatkins : do you want to open an issue with the other improvements you can think of ? Then I'll close this PR as it is.

**Comment by natashawatkins** [comment]
No problem - done in #322

**Comment by albop** [comment]
@mmcky : I did the merge but can't close the PR. What did you actually expect me to do ?

**Comment by natashawatkins** [comment]
@albop the PR appears to be closed :)

**Comment by albop** [comment]
OK thanks !

**Pull request merged**
