### PR TITLE
Update readthedocs to include all files in quantecon

### PR DESCRIPTION
**Pull request by mmcky**
See Issue #138

### CODE REVIEW

**Comment by mmcky** [comment]
Prior to merge this should be updated to include the new ``markov`` and ``random`` sub packages

**Comment by mmcky** [comment]
Updated to include all new sub packages. 
Review at: http://quanteconpy.readthedocs.org/en/update-doc-api/

**Comment by mmcky** [comment]
If anyone has any comments on the new documentation - let me know or submit a commit. 
Otherwise I will merge this branch tomorrow (12-Aug) - Thanks.

**Comment by oyamad** [comment]
Great, thanks @mmcky

I noticed the following:

* `util/array` and `util/random` have their pages ([this](http://quanteconpy.readthedocs.org/en/update-doc-api/util/array.html) and [this](http://quanteconpy.readthedocs.org/en/update-doc-api/util/random.html)), but it seems they cannot be reached from the side bar.

* [`cartesian`](http://quanteconpy.readthedocs.org/en/update-doc-api/tools/cartesian.html) still exists in addition to [`gridtools`](http://quanteconpy.readthedocs.org/en/update-doc-api/tools/gridtools.html), though it is not due to this readthedocs matter itself.

* [`version`](http://quanteconpy.readthedocs.org/en/update-doc-api/tools/version.html) does not need to show up?

**Comment by mmcky** [comment]
@oyamad Thanks for those points. I have addressed your comments.

* `util/array` and `util/random` have their pages ([this](http://quanteconpy.readthedocs.org/en/update-doc-api/util/array.html) and [this](http://quanteconpy.readthedocs.org/en/update-doc-api/util/random.html)), but it seems they cannot be reached from the side bar.

* [`version`](http://quanteconpy.readthedocs.org/en/update-doc-api/tools/version.html) does not need to show up?

I will leave the second to another PR to cleanup the ``cartesian.py`` file

**Comment by mmcky** [comment]
@cc7768 @spencerlyon2 Do either of you have an idea of why [this utilities page](http://quanteconpy.readthedocs.org/en/update-doc-api/random/utilities.html) only has one of two functions contained in the module. When I compile ``docs`` locally it has both functions - but they do not appear on ``readthedocs``!

**Comment by oyamad** [comment]
I am not sure, but is it related to Numba? As a side evidence, `simulate_linear_model` also does not appear in [lss.html](http://quanteconpy.readthedocs.org/en/update-doc-api/tools/lss.html).

**Comment by spencerlyon2** [comment]
I don't see why it isn't working.

This looks good to me: https://raw.githubusercontent.com/QuantEcon/QuantEcon.py/update-doc-api/docs/source/random/utilities.rst

**Comment by mmcky** [comment]
@oyamad thanks for the suggestion. I have added the docstring to the ``jitted`` function. 
I am officially stumped. The local build on my machine shows the missing functions in the html. It must be some ``readthedocs`` environment issue.

@spencerlyon2 I agree - the ``rst`` file is correct.

**Comment by mmcky** [comment]
All - I am merging this branch and will open an issue regarding the two missing ``numbafied`` functions for fixing. Given we have merged ``markov`` and ``util`` subpackage into master - we should probably update the ``readthedocs`` to reflect this change despite the issue. 

Merging now and opening separate issue.

**Pull request merged**
