### PR TITLE
Change Miniconda-latest to Miniconda3-latest

### PR DESCRIPTION
**Pull request by oyamad**
"Note: the Miniconda-latest-\* installers are Miniconda2-\* installers."
(https://repo.continuum.io/miniconda/)

### CODE REVIEW

**Comment by oyamad** [comment]
Previous error: https://travis-ci.org/QuantEcon/QuantEcon.py/builds/161823806

**Comment by oyamad** [comment]
The commit above is to propose to specify the version of Numba to be 0.28.1 for the moment, which is included in latest Anaconda.

**Comment by mmcky** [comment]
thanks @oyamad this looks ready to merge. 
I will merge this later today.

**Comment by mmcky** [comment]
@oyamad perhaps we should open an issue to track this forced dependency for version ``0.28.1`` to update at a future date.

**Comment by mmcky** [comment]
Ahh this will be tracked by: https://github.com/QuantEcon/QuantEcon.py/issues/269.

**Pull request merged**
