### PR TITLE
MAINT: Remove nose imports and use pytest

### LINKED ISSUE #539: Convert test suite from nosetests to pytest
It would be good to migrate our test suite from `nosetests` to `pytest`

https://docs.pytest.org/en/latest/

@Harveyt47 do you have time to look into this?

### LINKED ISSUE #603: `nosetests` does not work on windows CI job
We have the Github Actions job that runs on all three platforms for testing `quantecon`. `nosetests` seems to be working fine on Linux and mac, but not on windows. See https://github.com/QuantEcon/QuantEcon.py/runs/5148553158?check_suite_focus=true. It logs saying:
`Ran 0 tests in 5.394s`

I tried to figure out the problem but seems to be a platform-dependent issue from `nosetests`? Probably the best fix is to start moving towards `pytest`. One related answer on [StackOverflow](https://stackoverflow.com/questions/59288817/nosetests-not-recognized-on-windows) also suggests the same.

### PR DESCRIPTION
**Pull request by Smit-create**
Fixes #603  
Fixes #539

### CODE REVIEW

**Review by oyamad — COMMENTED** [review]
@Smit-create Thanks!

* Ready to run [`pytest`](https://github.com/Smit-create/QuantEcon.py/blob/bd4796246fb996c9a5c54055aa34a481d596e610/.github/workflows/test.yml#L48-L51) for the whole package and remove [`nose`](https://github.com/Smit-create/QuantEcon.py/blob/bd4796246fb996c9a5c54055aa34a481d596e610/.github/workflows/test.yml#L42-L45)?
* Apply your [fix](https://github.com/QuantEcon/QuantEcon.py/issues/539#issuecomment-1070896982) for `yield` tests?

**Comment by Smit-create** [comment]
> * Ready to run [`pytest`](https://github.com/Smit-create/QuantEcon.py/blob/bd4796246fb996c9a5c54055aa34a481d596e610/.github/workflows/test.yml#L48-L51) for the whole package and remove [`nose`](https://github.com/Smit-create/QuantEcon.py/blob/bd4796246fb996c9a5c54055aa34a481d596e610/.github/workflows/test.yml#L42-L45)?

Yeah, almost good to go. Just figuring out some fixes for moving the CI to pytest.



> * Apply your [fix](https://github.com/QuantEcon/QuantEcon.py/issues/539#issuecomment-1070896982) for `yield` tests?

Yeah, will do that.

**Comment by Smit-create** [comment]
We can now see that windows actually had some errors which were hidden since CI wasn't testing it somehow: see #603 
```
FAILED quantecon/tests/test_quad.py::TestQuadrect::test_quadrect_1d_H - Asser...
FAILED quantecon/tests/test_quad.py::TestQuadrect::test_quadrect_2d_H - Asser...
FAILED quantecon/tests/test_quad.py::TestQuadrect::test_quadrect_2d_H2 - Asse...
```

**Comment by oyamad** [comment]
Would it be possible that there is any overflow problem (on `int`?) on Windows?
(By the way, tests with conda-build are executed on Windows; see [here](https://github.com/QuantEcon/QuantEcon.py/runs/5715855957).)

The outputs by adding `print(self.data1d['H'])` and `print(self.ml_data1d['H'])` to `test_quadrect_1d_H` in `test_quad.py` on my Mac machine (they coincide, so the test passes):

```
Function  Number of Nodes
f1        5                  2.038668
          11                 2.304388
          21                 2.326613
          51                 2.376437
          101                2.357948
          401                2.350112
f2        5                  0.567056
          11                 0.522468
          21                 0.541228
          51                 0.548324
          101                0.550358
          401                0.548292
f3        5                  1.231611
          11                 1.344101
          21                 1.347244
          51                 1.337201
          101                1.332924
          401                1.333956
Name: H, dtype: float64
```

Compare the 6th, 12th, and 18th entries of the `x` array in the [failure log](https://github.com/QuantEcon/QuantEcon.py/runs/5715855913?check_suite_focus=true#step:6:78), which all correspond to the rows with `401` nodes in the above outputs.

Any idea? @sglyon

**Comment by Smit-create** [comment]
> (By the way, tests with conda-build are executed on Windows; see [here](https://github.com/QuantEcon/QuantEcon.py/runs/5715855957).)

They aren't working. See the log at the bottom, it shows:
```
Ran 0 tests in 1.541s
```

**Comment by oyamad** [comment]
> They aren't working. See the log at the bottom, it shows:

Right, I wanted to write "tests with conda-build are NOT executed on Windows"...

**Comment by oyamad** [comment]
It seems I was right: see https://github.com/QuantEcon/QuantEcon.py/runs/5731337967#step:6:53.
You might cherry pick 55cb67b71521d96166e82576d274d12115173999.

**Comment by oyamad** [comment]
Maybe this db2066e765bb04823a75bc882d813ba12ece2eff is better.

**Comment by Smit-create** [comment]
Thanks @oyamad. Tests pass now. This PR now looks ready to go in. We can suppress `pytest` warnings and use `pytest` on `conda-build` as a follow of this PR.

**Review by oyamad — APPROVED** [review]
@Smit-create Many thanks!

Not closing #603 and #539 yet?

**Comment by mmcky** [comment]
thanks @Smit-create and @oyamad

**Comment by Smit-create** [comment]
> Not closing #603 and #539 yet?

No problem. I will make the follow-up PR soon.

**Pull request merged**
