### PR TITLE
Add rouwenhorst method for approx AR(1) with MC

### PR DESCRIPTION
**Pull request by sglyon**
NOTE: This needs tests...

### CODE REVIEW

**Comment by jstac** [comment]
@sglyon Thanks, appreciated.
@mmcky Perhaps one of our RAs can fix this and write a test.  @lbui01 could probably do it.

**Comment by sglyon** [comment]
I should have pointed out that this may have been written by either @cc7768  or I -- it was for a homework assignment we had a couple years ago and I don't remember now who wrote which parts...

**Comment by lbui01** [comment]
@jstac @mmcky  - I'm happy to do this.

**Comment by jstac** [comment]
@lbui01 Great, thanks.  If you explore the library you will get a feeling for how the tests are organized.  Feel free to post questions.

@sglyon @cc7768 , @lbui01 is based here with us.  He is doing well but will benefit from feedback on his PRs.

**Comment by mmcky** [comment]
@lbui01 let's discuss when we meet up this morning re: git

**Comment by lbui01** [comment]
Hi @sglyon  - 

I have added a test for the rouwenhorst method.  It's largely the same as the test for the tauchen test, except i've added a control case where i've pre-calculated the MC and state space values for pre-specified parameters.

Any comments would be appreciated!

I've also changed the _ _ init _ _ files in order to load the rouwenhorst from approximation.py.

**Comment by mmcky** [comment]
thanks @lbui01. This looks good to me. 

@sglyon when convenient could you review and then I will merge.

**Comment by sglyon** [comment]
Looks great!

**Pull request merged**
