### PR TITLE
ENH: add njit interpolation functions

### PR DESCRIPTION
**Pull request by mmcky**
This PR adds the following interpolation functions

- `interp` that accepts x as `float` or `np.array`

and the following internal functions:

- `_interpf` that accepts x as `float`
- `_interpa` that accepts x as `np.array`

### CODE REVIEW

**Comment by oyamad** [comment]
`np.interp` is available through `Numba`: see https://numba.pydata.org/numba-doc/dev/reference/numpysupported.html.
Any advantage over that here?

**Comment by mmcky** [comment]
> `np.interp` is available through `Numba`: see https://numba.pydata.org/numba-doc/dev/reference/numpysupported.html. Any advantage over that here?

thanks @oyamad probably not -- i didn't realise it was supported. 

As we have decided to revert the order of arguments to match the numpy order we should use the numba built-in.

**Comment by mmcky** [comment]
cc @jstac

**Comment by jstac** [comment]
Thanks @mmcky heading to the hospital now.

**Comment by mmcky** [comment]
> Thanks @mmcky heading to the hospital now.

Hope all goes well. Thanks @jstac

**Comment by jstac** [comment]
Thanks @oyamad .

Sorry @mmcky , my bad.  perhaps we can test if swapping for the numpy version degrades performance or causes any issues in one or two lectures that are currently using jitted functions plus the version from `interpolation`.  If all is good we can close this PR and swap every 1d interp to the numpy version.

**Pull request closed without merging**
