### PR TITLE
Travis: Add macOS to the build matrix

### LINKED ISSUE #359: Add OSX to travis.yml configuration
Add OS X for platform specific testing in the ``travis.yml`` configuration file. 

```
os:
  - linux
  - osx
```

but the ``before_install`` needs to be made os independent.

https://docs.travis-ci.com/user/multi-os/

### PR DESCRIPTION
**Pull request by rht**
This fixes #359.

### CODE REVIEW

**Comment by rht** [comment]
Note: the version shipped in xcode10 is 3.7.

**Comment by rht** [comment]
The first commit setup works fine (by install hdf5 via homebrew instead of conda), however, the machine was too slow to run the timing test.

**Comment by mmcky** [comment]
thanks @rht -- this is great. I will check through the diff tomorrow and merge.

**Comment by rht** [comment]
OK, I found the `test_rotated_hyper_ellipsoid` to be non-deterministic though, in that sometimes on darwin it is fulfilled/failed, in that I can't write it as a test-expect-fail.

**Comment by mmcky** [comment]
hey @rht we have had tests running on linux for quite some time. I'm not sure why you're getting non-deterministic results. Are you sure its not just a tolerance issue?

**Comment by rht** [comment]
Otherwise, I can't explain the error in the commit "TestTicTacToc: Skip test_loop and test_timer for darwin". There was an error of ~1e-5.

**Comment by mmcky** [comment]
thanks @rht for the PR! I will merge this and take a look at `tic` `tac` `toc` issue for `darwin` when I get a chance. It's tested on the linux side anyway.

**Pull request merged**
