### PR TITLE
Numba improvements

### PR DESCRIPTION
**Pull request by spencerlyon2**
I'm just opening this as a PR so that it is easy to see what has been changed. We can still push to the branch to make more changes to the PR. 

I have _no_ intention of merging this myself.

### CODE REVIEW

**Comment by oyamad** [comment]
@spencerlyon2 Thanks for issuing the PR!

Summary of changes and issues to discuss:

0. `gth_solve.py`: The main part is jitted in a new function called `_gth_solve_jit` with nopython mode; if not numba_installed, the previous NumPy version is executed. The test does not cover the NumPy version. See #103 for details ([this](https://github.com/QuantEcon/QuantEcon.py/pull/103#issuecomment-95621781) in particular).

0. `mc_tools.py`:  `mc_sample_path` is autojitted if numba_installed; a NumPy version `mc_sample_path_numpy` is also implemented, which overwrites `mc_sample_path` if not numba_installed. The only difference between the two version is that the former uses the custom `searchsorted`, which is contained in `utilities.py`, while the latter uses `np.searchsorted`. See #137 for details.

0. `utilities.py`: Contains `searchsorted`, which is a jitted and simplified version of `np.searchsorted`; it is an alias of `np.searchsorted` if not numba_installed. This function will no longer be need and should be discarded once `np.searchsorted` is supported by Numba.

0. `numba_import_fail_message` is in `common_messages.py`; `numba_installed ` is defined with `try from Numba import jit except ...` in `external.py`.

0. Issues on `cartesian` are to be discussed in #143.

0. The issue of keeping/preparing a NumPy counterpart for each routine implemented with Numba, one of the main issues in #132. Will we drop support for NumPy version sometime in the future, and if so, at what occasion? (I feel somehow uneasy when I see the duplications...)

0. These may belong to other PRs:
  * Possible changes in the API of `MarkovChain`/`mc_sample_path`: see [this](https://github.com/QuantEcon/QuantEcon.py/issues/137#issuecomment-93534791) and [this](https://github.com/QuantEcon/QuantEcon.py/issues/137#issuecomment-95180890).
  * Support for sparse matrices in `MarkovChain` (I have code for `mc_sample_path` but not yet for `gth_solve`).

0. This is not really important, but the "coverage" as displayed on the top page gets decreased as we write more Numba implemented code, since the `coverage` module inspects the jitted functions to not covered by the tests. See [Code coverage of jitted functions - Google Groups](https://groups.google.com/a/continuum.io/forum/#!topic/numba-users/CqN2zkGb9nA).

**Comment by mmcky** [comment]
@oyamad Excellent summary. I think most of these discussions points are captured in other open issues now - so I don't see any reason not to merge this in. Do you? 

Point 7 (i). I have opened an issue to track this (#146) based on content in #137 
Point 7 (ii). I have opened an issue to track this (#145). 

Point 8. Interesting issue - I agree not entirely important at this stage - but good to be aware of. Thanks for pointing this out.

**Comment by oyamad** [comment]
@mmcky thanks.

I still have a concern about the duplication in `mc_tools.py`. I think `mc_sample_path_numpy` is not necessary and the following is sufficient:

```python
def mc_sample_path(P, init=0, sample_size=1000):
    """
    See Section: DocStrings below
    """
    n = len(P)

    # CDFs, one for each row of P
    cdfs = np.empty((n, n), order='C')  # see issue #137#issuecomment-96128186
    np.cumsum(P, axis=-1, out=cdfs)

    # Random values, uniformly sampled from [0, 1)
    u = np.random.random(size=sample_size)

    # === set up array to store output === #
    X = np.empty(sample_size, dtype=int)
    if isinstance(init, int):
        X[0] = init
    else:
        cdf0 = np.cumsum(init)
        X[0] = searchsorted(cdf0, u[0])

    # === generate the sample path === #
    for t in range(sample_size-1):
        X[t+1] = searchsorted(cdfs[X[t]], u[t+1])

    return X

if numba_installed:
    mc_sample_path = jit(mc_sample_path)
```

If not numba_installed, `searchsorted` works as `np.searchsorted` (with `side='right'`), as defined in `utilities.py`.

**Comment by mmcky** [comment]
@oyamad I see what you are saying now - thanks. I think this is a good idea.  Effectively it boils down to moving the ``numpy`` vs ``numba`` comparison down a level to the now internal ``searchsorted`` utility functions. So we should update the test to compare jitted ``searchsorted`` with the numpy ``searchsorted`` (with ``side="right"``) to ensure both give the same result over time. In your implementation above the rest of ``mc_sample_path`` is exactly the same logically jitted or not.

The only downside I see is in this implementation we won't be able to check the function ``mc_sample_path`` final output between the ``jit`` version and the ``non jit`` version easily - but that would only effectively be checking for jit errors which are probably less of an issue versus logic errors etc.  

@jstac I will leave the final decision with you. But @oyamad suggestion does reduce duplication in this special case. 

**Performance:**
I had a quick look at performance (http://nbviewer.ipython.org/github/mmcky/work-notebooks/blob/master/quantecon/PerformanceCheckMCTools.ipynb). Sorry didn't suppress %timeit text but the graphs in ``Out[7]`` and ``Out[15]`` suggests that ``numba`` function is best for anything greater than a sample size of ~70. ``localB`` is what would happen in the case of no ``numba`` installed and is the slowest. Interestingly the non-numpy ``looped`` version of searchsorted runs faster even in pure python which is ``localA``. I am not sure why this is.

**Comment by oyamad** [comment]
@mmcky Thank you for the performance comparison. It is very interesting.
I suspect that `qe.numpy` and `localB` would be faster than `localA` for matrices of larger size.

**Comment by mmcky** [comment]
@oyamad Yeah I think you are right. Last night I had a quick look in our library for a simple utility for producing a ``Transition Matrix`` of size n. I didn't see one - I could produce some performance checks through the matrix dimensions this afternoon.

**Comment by mmcky** [comment]
@oyamad Indeed. I added a really simple test which is just using a random matrix ``P`` with each row normalised  to 1. ``localB`` is much better than ``localA``. (http://nbviewer.ipython.org/github/mmcky/work-notebooks/blob/master/quantecon/PerformanceCheckMCTools.ipynb)

**Comment by jstac** [comment]
@oyamad @mmcky You've done a lot of work.  It's looking really good. I like the look of the code and I'm keen to merge this.  

I agree with @oyamad 's suggestion about cutting `mc_sample_path_numpy`.  There's no need for it.  As long as the home grown version of `searchsorted` is properly tested --- which it is --- there's no need to keep `mc_sample_path_numpy` just for the sake of testing.

So I propose that we adopt @oyamad 's suggestion, cut this function, and then merge.

**Comment by oyamad** [comment]
I deleted `mc_sample_path_numpy` and `test_mc_sample_path_functions`. Now no test is there for `mc_sample_path`.

**Comment by jstac** [comment]
Thanks for all this work.  I'll merge now and at the same time open an issue to add a test for `mc_sample_path`.  Great to have this merged!

**Comment by spencerlyon2** [comment]
Alt Text

**Pull request merged**
