### PR TITLE
[Refactor]: Make random methods compatible to RandomGenerator

### PR DESCRIPTION
**Pull request by Smit-create**

### CODE REVIEW

**Comment by oyamad** [comment]
@Smit-create Will you keep `randint` as is in this PR (restrict only to `rand`/`random_sample` and `randn`)?

Changes of `randint` should be made as commits added to the branch [`np-random-generator`](https://github.com/QuantEcon/QuantEcon.py/tree/np-random-generator). (Do you have a write access?)

**Comment by oyamad** [comment]
Sorry, `rand(d0, d1, ..., dn)` has to be replaced with `random((d0, d1, ..., dn))`
(or `random(size=(d0, d1, ..., dn))`).

**Comment by Smit-create** [comment]
> (Do you have a write access?)

Yes, I have access. I will push `randint` changes in that PR.

**Review by oyamad — APPROVED** [review]
Looks good to me!

**Pull request merged**
