### PR TITLE
MAINT: Auto-detect version from `version.py` in `setup.py`

### PR DESCRIPTION
**Pull request by Smit-create**
With the current patch, we just need to maintain the version on `version.py`. `setup.py` detects version from this file while building and installing.
cc @mmcky

### CODE REVIEW

**Comment by mmcky** [comment]
thanks @Smit-create I think the ideal way to go is to add a `__version__ = '0.5.2'` in the `__init__.py` file at the base level of the project. I have seen in other projects we can then infer that attribute in the `setup.py` file.

**Comment by Smit-create** [comment]
> thanks @Smit-create I think the ideal way to go is to add a `__version__ = '0.5.2'` in the `__init__.py` file at the base level of the project. I have seen in other projects we can then infer that attribute in the `setup.py` file.

That sounds good to me. Let me try it that way.

**Comment by Smit-create** [comment]
I guess the previous fix was working fine!

**Comment by Smit-create** [comment]
Woah! CI is green

**Comment by mmcky** [comment]
Love your work on this @Smit-create thank you! ❤️

**Comment by Smit-create** [comment]
Thanks a lot!

**Pull request merged**
