### PR TITLE
 Fix tac, toc, loop_timer to return float

### LINKED ISSUE #386: Return value of timing functions
* I think `toc` and `tac` should return a `float`, and there is no point of returning a `str`.
* `digits` should be used to control the number of digits of the **printed** value, not of the returned value.

See also #322.

### PR DESCRIPTION
**Pull request by oyamad**
Close #386

### CODE REVIEW

**Comment by mmcky** [comment]
@oyamad from a backwards compatibility perspective are there any changes to usage? 
I don't think so as I see you've used `verbose=True` as a default so the floats will print.

**Comment by mmcky** [comment]
thanks @oyamad this looks good.

**Comment by oyamad** [comment]
Yes, this is backward incompatible:

| Version  | Output type     | Print option   | Output option |
|----------|-----------------|----------------|---------------|
| -0.3.6.2 | `float`         | -              | -             |
| 0.3.7    | `str` or `None` | `print_output` | `output`      |
| This PR  | `float`         | `verbose`      | -             |

**Comment by mmcky** [comment]
@oyamad thanks. This is mainly used as a utility so I think that is fine. I will just do a search across the repo to make sure there are no other changes.

**Pull request merged**
