### PR TITLE
FIX: Update license file from BSD-3 to MIT

### PR DESCRIPTION
**Pull request by mmcky**
This PR updates the license to `MIT`

### CODE REVIEW

**Comment by mmcky** [comment]
@jstac @oyamad @thomassargent30 this is a change in LICENSE so I wanted to seek approval from all lead developers for this change. Thank you.

**Comment by oyamad** [comment]
@mmcky I have no preference between BSD-3 and MIT, but just wondered why we change the LICENSE rather than the description in the paper?

**Comment by mmcky** [comment]
@oyamad good question. @jstac do you have a preference between `MIT` and `BSD-3`? 
I see more projects going to `MIT` perhaps because the license is slightly simpler.

**Comment by jstac** [comment]
@mmcky @oyamad I hear that MIT is simpler and more popular.  I would be happy to see the change but I don't have strong opinions.  Please feel free to make the call.

**Review by jstac — APPROVED** [review]

**Comment by jstac** [comment]
To be clear, @mmcky and @oyamad are joint maintainers and so have the final say.  Since @oyamad has no objection, it seems fine to merge...?

**Review by oyamad — APPROVED** [review]

**Comment by mmcky** [comment]
thanks @oyamad and @jstac appreciate the discussion around license. I will merge this now and move to MIT.

**Pull request merged**
